# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1d52b1fcbcce4b1fa1ed8128412d2a7b5019e6eda632474c772d7b7b019bc1190b8b186d3d97e6514754d52a6c5b1499449e174a40a5bf1a25d7e3096788ac9

test:
  secret_key_base: b0d8bc8b3b56d34bddba281d7dbf3358d6e2cfffe87277ca1878550a87198009c6d10ad00d7742d6b5c712a0eabb3804b0c6846d51522ed72366918d4ee0e10d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
